# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.FileField(blank=True, null=True, upload_to=b'avatar/%Y/%m/%d')),
                ('fecha_reg', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.NullBooleanField(verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('texto', models.TextField(blank=True, max_length=500, null=True, verbose_name='Texto')),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.NullBooleanField(verbose_name='Activado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.NullBooleanField(verbose_name='Activado')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Comentario_m')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario_m',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Publicaciones_m'),
        ),
        migrations.AddField(
            model_name='comentario_m',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
